name: Fetch Remote Jobs

on:
  schedule:
    # Run at 06:00 and 18:00 UTC daily (adjust for your timezone)
    - cron: "0 6,18 * * *"
  workflow_dispatch: {}   # Allow manual triggering

concurrency:
  group: fetch-jobs
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm ci --only=production || npm install --only=production || true
          fi

      - name: Fetch Job Listings
        env:
          USER_AGENT: "RemotelyYouBot/1.0 (+https://remotelyyou.com)"
        run: |
          echo "Starting job fetch process..."
          npm run fetch
          
          # Check if jobs.json changed
          if git diff --quiet -- site/public/jobs.json; then
            echo "NO_CHANGE=true" >> $GITHUB_ENV
            echo "No changes detected in jobs.json"
          else
            echo "Changes detected in jobs.json"
            git diff --stat site/public/jobs.json
          fi

      - name: Commit Updated Jobs
        if: env.NO_CHANGE != 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add only the jobs.json file
          git add site/public/jobs.json
          
          # Get job count for commit message
          JOB_COUNT=$(node -e "
            const fs = require('fs');
            try {
              const data = JSON.parse(fs.readFileSync('site/public/jobs.json', 'utf8'));
              console.log(data.jobs ? data.jobs.length : 0);
            } catch (e) {
              console.log('0');
            }
          ")
          
          git commit -m "chore: update jobs.json with ${JOB_COUNT} remote jobs

          - Updated at: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          - Beginner-friendly positions only
          - Auto-generated by GitHub Actions
          
          [skip ci]"
          
          git push origin main
          
          echo "Successfully pushed updated jobs.json with ${JOB_COUNT} jobs"

      - name: Job Summary
        if: always()
        run: |
          echo "## Job Fetch Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "$NO_CHANGE" = "true" ]; then
            echo "✅ **Status:** No changes detected" >> $GITHUB_STEP_SUMMARY
            echo "📊 **Action:** No commit necessary" >> $GITHUB_STEP_SUMMARY
          else
            JOB_COUNT=$(node -e "
              const fs = require('fs');
              try {
                const data = JSON.parse(fs.readFileSync('site/public/jobs.json', 'utf8'));
                console.log(data.jobs ? data.jobs.length : 0);
              } catch (e) {
                console.log('0');
              }
            ")
            echo "✅ **Status:** Jobs updated successfully" >> $GITHUB_STEP_SUMMARY
            echo "📊 **Job Count:** ${JOB_COUNT} positions" >> $GITHUB_STEP_SUMMARY
            echo "💾 **Action:** Committed to repository" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "🕒 **Last Run:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "🔄 **Next Run:** Scheduled for 06:00 and 18:00 UTC daily" >> $GITHUB_STEP_SUMMARY